/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shivam.learns;

import shivam.learns.java.lambda.LearnLambda;
import shivam.learns.java.lambda.PrintAnything;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        LearnLambda learnLambda = new LearnLambda();

        learnLambda.print();



    }
    public static void print(PrintAnything printAnything){
        System.out.println("Hey");
    }
}
